// <auto-generated />
using System;
using ClientManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20260506165405_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientManager.Core.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClientType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("INN")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("INN")
                        .IsUnique()
                        .HasFilter("[DeletedDate] IS NULL");

                    b.ToTable("Clients", t =>
                        {
                            t.HasCheckConstraint("CK_Client_INN_Format", "[INN] NOT LIKE '%[^0-9]%' AND (([ClientType] = 1 AND LEN([INN]) = 10) OR ([ClientType] = 2 AND LEN([INN]) = 12))");
                        });
                });

            modelBuilder.Entity("ClientManager.Core.Domain.Entities.ClientFounder", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FounderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClientType")
                        .HasColumnType("int");

                    b.HasKey("ClientId", "FounderId");

                    b.HasIndex("FounderId");

                    b.HasIndex("ClientId", "ClientType");

                    b.ToTable("ClientFounders", t =>
                        {
                            t.HasCheckConstraint("CK_ClientFounder_LegalEntityOnly", "[ClientType] = 1");
                        });
                });

            modelBuilder.Entity("ClientManager.Core.Domain.Entities.Founder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("INN")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("INN")
                        .IsUnique()
                        .HasFilter("[DeletedDate] IS NULL");

                    b.ToTable("Founders", t =>
                        {
                            t.HasCheckConstraint("CK_Founder_INN_Format", "LEN([INN]) = 12 AND [INN] NOT LIKE '%[^0-9]%'");
                        });
                });

            modelBuilder.Entity("ClientManager.Core.Domain.Entities.ClientFounder", b =>
                {
                    b.HasOne("ClientManager.Core.Domain.Entities.Founder", "Founder")
                        .WithMany("ClientFounders")
                        .HasForeignKey("FounderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClientManager.Core.Domain.Entities.Client", "Client")
                        .WithMany("ClientFounders")
                        .HasForeignKey("ClientId", "ClientType")
                        .HasPrincipalKey("Id", "ClientType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Founder");
                });

            modelBuilder.Entity("ClientManager.Core.Domain.Entities.Client", b =>
                {
                    b.Navigation("ClientFounders");
                });

            modelBuilder.Entity("ClientManager.Core.Domain.Entities.Founder", b =>
                {
                    b.Navigation("ClientFounders");
                });
#pragma warning restore 612, 618
        }
    }
}
