<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClientManager.Core.Services\ClientManager.Core.Services.csproj" />
    <ProjectReference Include="..\ClientManager.Infrastructure.Persistence\ClientManager.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\ClientManager.Infrastructure.Presentation\ClientManager.Infrastructure.Presentation.csproj" />
    <ProjectReference Include="..\LoggingService\LoggingService.csproj" />
  </ItemGroup>

</Project>
