<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
	  <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
	  <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="10.0.7" />
	  <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ClientManager.Core.Services.Abstractions\ClientManager.Core.Services.Abstractions.csproj" />
	  <ProjectReference Include="..\LoggingService\LoggingService.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <InternalsVisibleTo Include="ClientManager.UnitTests" />
	</ItemGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DocumentationFile>ClientManager.Infrastructure.Presentation.xml</DocumentationFile>
		<OutputPath></OutputPath>
		<NoWarn>1701;1702;1591</NoWarn>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<NoWarn>1701;1702;1591</NoWarn>
	</PropertyGroup>

</Project>
