<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClientManager.Core.Domain\ClientManager.Core.Domain.csproj" />
    <ProjectReference Include="..\ClientManager.Core.Services.Abstractions\ClientManager.Core.Services.Abstractions.csproj" />
    <ProjectReference Include="..\LoggingService\LoggingService.csproj" />
  </ItemGroup>

</Project>
