<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClientManager.Core.Domain\ClientManager.Core.Domain.csproj" />
    <ProjectReference Include="..\ClientManager.Core.Services.Abstractions\ClientManager.Core.Services.Abstractions.csproj" />
    <ProjectReference Include="..\LoggingService\LoggingService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ClientManager.UnitTests" />
  </ItemGroup>

</Project>
